"""Generate the data-driven results tables as LaTeX (booktabs) from the benchmark
files, so they regenerate verbatim after a fresh benchmark run. Emits complete
`table` floats (caption + label) into paper/tables/.

Produces:
  tab_success_ur5.tex      success %, UR5, per scenario         (<- master CSV)
  tab_success_franka.tex   success %, Franka, per scenario      (<- master CSV)
  tab_latency.tex          KineticFold vs TRAC-IK, 4 cells      (<- master CSV)
  tab_collision_ur5.tex    UR5 real-mesh self-collision         (<- collision CSV)
  tab_dof_scaling.tex      clean% vs DOF (flagship companion)   (<- usecase JSON)

Static, hand-authored tables (isomorphism, robots, thresholds, baselines) live in
paper/tables/tables_static.tex and are NOT generated here.

Requires booktabs in the preamble:  \\usepackage{booktabs}
Run:  python make_tables.py [--csv ...] [--collision-csv ...] [--json ...]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _style as S

CELLS = [("ur5", "open_space"), ("ur5", "cluttered"),
         ("franka_panda", "open_space"), ("franka_panda", "cluttered")]


def f1(x) -> str:
    return "--" if (x != x) else f"{x:.1f}"


def bold(cells):
    return [f"\\textbf{{{c}}}" for c in cells]


def write_table(name, caption, label, colspec, header, body, note=None):
    S.TABLE_DIR.mkdir(parents=True, exist_ok=True)
    L = [
        "% Auto-generated by paper/figures/make_tables.py -- regenerate, do not hand-edit.",
        "\\begin{table}[t]", "\\centering",
        f"\\caption{{{caption}}}", f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{colspec}}}", "\\toprule",
        " & ".join(header) + " \\\\", "\\midrule",
    ]
    L += [" & ".join(r) + " \\\\" for r in body]
    L += ["\\bottomrule", "\\end{tabular}"]
    if note:
        L.append(f"\\\\[2pt]\n{{\\footnotesize {note}}}")
    L.append("\\end{table}")
    (S.TABLE_DIR / name).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"  wrote tables/{name}")


# --------------------------------------------------------------------------- #
def tab_success(rows, robot, name, caption, label):
    solvers = S.present_solvers(rows, robot)
    scen = [s for s in S.SCENARIOS if S.cell(rows, robot, s)]
    body = []
    for sid in solvers:
        vals = [f1(S.cell(rows, robot, sc).get(sid, {}).get("success_pct", float("nan")))
                for sc in scen]
        row = [S.label(sid)] + vals
        body.append(bold(row) if sid == S.HERO else row)
    header = ["Solver"] + [S.SCEN_LABEL[s] for s in scen]
    write_table(name, caption, label, "l" + "r" * len(scen), header, body)


def tab_latency(rows, name):
    body = []
    for robot, scen in CELLS:
        c = S.cell(rows, robot, scen)
        arm = {"ur5": "UR5", "franka_panda": "Franka"}[robot]
        for sid in ("trac_ik_style", "protein_fast"):
            r = c.get(sid)
            if not r:
                continue
            cells = [f"{arm}/{S.SCEN_LABEL[scen]}", S.label(sid),
                     f1(r["mean_ms"]), f1(r["p50_ms"]), f1(r["p95_ms"]), f1(r["p99_ms"])]
            body.append(bold(cells) if sid == S.HERO else cells)
    write_table(name,
                "Latency (ms): easy vs.\\ hard regime, KineticFold vs.\\ TRAC-IK.",
                "tab:latency", "llrrrr",
                ["Arm/scenario", "Solver", "Mean", "p50", "p95", "p99"], body,
                note="Wall-clock; OS scheduling noise on mean/p95/p99.")


def tab_collision(rows, name):
    solvers = [s for s in ["protein_ik", "multi_start", "trac_ik_style", "protein_fast", "protein_raw"]
               if any(r["robot"] == "ur5" and r["solver"] == s for r in rows)]
    scen = [s for s in S.SCENARIOS if S.cell(rows, "ur5", s)]
    body = []
    for sid in solvers:
        succ = [f1(S.cell(rows, "ur5", sc).get(sid, {}).get("success_pct", float("nan")))
                for sc in scen]
        pbc = [f1(S.cell(rows, "ur5", sc).get(sid, {}).get("pb_collision_pct", float("nan")))
               for sc in scen]
        clr_c = S.cell(rows, "ur5", "cluttered").get(sid, {}).get("pb_mean_clearance_m", float("nan"))
        cells = [S.label(sid)] + succ + pbc + [f"{clr_c*1000:+.1f}" if clr_c == clr_c else "--"]
        body.append(bold(cells) if sid == S.HERO else cells)
    header = (["Solver"] + [f"succ {S.SCEN_LABEL[s]}" for s in scen]
              + [f"PB {S.SCEN_LABEL[s]}" for s in scen] + ["clr c (mm)"])
    write_table(name,
                "UR5 real-mesh self-collision. succ = success \\%; "
                "PB = PyBullet self-collision \\%; clr = mean clearance on cluttered.",
                "tab:collision_ur5", "l" + "r" * (len(header) - 1), header, body,
                note="MuJoCo agrees (see \\texttt{mj\\_collision\\_pct}); "
                     "collision reported as a ranking, not an absolute rate.")


def tab_langevin(rows, name, robot="ur5"):
    """LangevinFold vs. the field on UR5: per-scenario real-mesh collision, worst-case
    success, and latency (from the hardest scenario). From the separate small-scale run."""
    order = ["protein_raw", "protein_fast", "trac_ik_style", "multi_start", "protein_ik"]
    solvers = [s for s in order if any(r["robot"] == robot and r["solver"] == s for r in rows)]
    scen = [s for s in S.SCENARIOS if S.cell(rows, robot, s)]
    hard = "cluttered" if "cluttered" in scen else (scen[-1] if scen else None)
    body = []
    for sid in solvers:
        pbc = [f1(S.cell(rows, robot, sc).get(sid, {}).get("pb_collision_pct", float("nan")))
               for sc in scen]
        succs = [S.cell(rows, robot, sc).get(sid, {}).get("success_pct", float("nan")) for sc in scen]
        succs = [s for s in succs if s == s]
        rr = S.cell(rows, robot, hard).get(sid, {}) if hard else {}
        cells = ([S.label(sid)] + pbc
                 + [f1(min(succs) if succs else float("nan")),
                    f1(rr.get("mean_ms", float("nan"))), f1(rr.get("p99_ms", float("nan")))])
        body.append(bold(cells) if sid == "protein_raw" else cells)
    header = ["Solver"] + [f"PB {S.SCEN_LABEL[s]}" for s in scen] + ["succ (min)", "mean ms", "p99 ms"]
    write_table(name,
                "LangevinFold vs.\\ the field on UR5 (separate small-scale run). "
                "PB = PyBullet self-collision \\%; latency from the cluttered cell.",
                "tab:langevin", "l" + "r" * (len(header) - 1), header, body,
                note="LangevinFold gives the lowest real-mesh collision at seconds/solve "
                     "(MuJoCo agrees; see \\texttt{mj\\_collision\\_pct}).")


def tab_dof(json_path, name):
    E = json.loads(Path(json_path).read_text(encoding="utf-8"))["E"]
    dofs = sorted({int(r["dof"]) for r in E})

    def clean_of(sid, d):
        return next((r["clean_pct"] for r in E if int(r["dof"]) == d and r["solver"] == sid),
                    float("nan"))
    body = []
    for d in dofs:
        kf, tr = clean_of("protein_fast", d), clean_of("trac_ik_style", d)
        ratio = f"{kf/tr:.1f}$\\times$" if tr > 0 else ("only solver" if kf > 0 else "--")
        body.append([str(d), f1(kf), f1(tr), ratio])
    write_table(name,
                "Single-shot clean-solve rate (\\%) vs.\\ DOF, planar arm. "
                "Both solvers reach the target $\\approx$100\\%; the gap is self-collision.",
                "tab:dof_scaling", "rrrr",
                ["DOF", "KineticFold", "TRAC-IK", "ratio"], body,
                note="Native, apples-to-apples: KineticFold runs as its C++/Eigen port "
                     "and TRAC-IK as the genuine TRACLabs C++ library (\\texttt{tracikpy}), "
                     "each solving the identical DH chain.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default=str(S.DEFAULT_MASTER_CSV))
    ap.add_argument("--collision-csv", default=str(S.DEFAULT_COLLISION_CSV))
    ap.add_argument("--langevin-csv", default=str(S.DEFAULT_LANGEVIN_CSV))
    ap.add_argument("--json", default=str(S.DEFAULT_USECASE_JSON))
    args = ap.parse_args()

    master = S.load_rows(args.csv)
    tab_success(master, "ur5", "tab_success_ur5.tex",
                "Success rate (\\%), UR5.", "tab:success_ur5")
    if any(r["robot"] == "franka_panda" for r in master):
        tab_success(master, "franka_panda", "tab_success_franka.tex",
                    "Success rate (\\%), Franka Panda (corrected kinematics).",
                    "tab:success_franka")
    tab_latency(master, "tab_latency.tex")
    tab_dof(args.json, "tab_dof_scaling.tex")

    try:
        coll = S.load_rows(args.collision_csv)
        tab_collision(coll, "tab_collision_ur5.tex")
    except FileNotFoundError as e:
        print(f"  [skip] tab_collision_ur5: {e}")

    # tab_langevin is parked for future work — not emitted by the default run.
    # To generate it: uncomment below after running bench/langevin_benchmark.py.
    # try:
    #     tab_langevin(S.load_rows(args.langevin_csv), "tab_langevin.tex")
    # except FileNotFoundError:
    #     print("  [skip] tab_langevin: run bench/langevin_benchmark.py first")


if __name__ == "__main__":
    main()
