"""Generate the data-driven results tables as LaTeX (booktabs) from the benchmark
files, so they regenerate verbatim after a fresh benchmark run. Emits complete
`table` floats (caption + label) into paper/tables/.

Produces:
  tab_success_ur5.tex      success %, UR5, per scenario         (<- master CSV)
  tab_success_franka.tex   success %, Franka, per scenario      (<- master CSV)
  tab_latency.tex          KineticFold vs TRAC-IK, 4 cells      (<- master CSV)
  tab_collision_ur5.tex    UR5 real-mesh self-collision         (<- collision CSV)
  tab_dof_scaling.tex      clean% vs DOF (flagship companion)   (<- usecase JSON)

Static, hand-authored tables (isomorphism, robots, thresholds, baselines) live in
paper/tables/tables_static.tex and are NOT generated here.

Requires booktabs in the preamble:  \\usepackage{booktabs}
Run:  python make_tables.py [--csv ...] [--collision-csv ...] [--json ...]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _style as S

CELLS = [("ur5", "open_space"), ("ur5", "cluttered"),
         ("franka_panda", "open_space"), ("franka_panda", "cluttered")]


def f1(x) -> str:
    return "--" if (x != x) else f"{x:.1f}"


def bold(cells):
    return [f"\\textbf{{{c}}}" for c in cells]


def write_table(name, caption, label, colspec, header, body, note=None, star=False):
    """``star=True`` emits table* (full page width) for tables too wide for one column."""
    S.TABLE_DIR.mkdir(parents=True, exist_ok=True)
    env = "table*" if star else "table"
    L = [
        "% Auto-generated by paper/figures/make_tables.py -- regenerate, do not hand-edit.",
        f"\\begin{{{env}}}[t]", "\\centering",
        f"\\caption{{{caption}}}", f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{colspec}}}", "\\toprule",
        " & ".join(header) + " \\\\", "\\midrule",
    ]
    L += [" & ".join(r) + " \\\\" for r in body]
    L += ["\\bottomrule", "\\end{tabular}"]
    if note:
        L.append(f"\\\\[2pt]\n{{\\footnotesize {note}}}")
    L.append(f"\\end{{{env}}}")
    (S.TABLE_DIR / name).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"  wrote tables/{name}")


# --------------------------------------------------------------------------- #
def tab_success(rows, robot, name, caption, label):
    solvers = S.present_solvers(rows, robot)
    scen = [s for s in S.SCENARIOS if S.cell(rows, robot, s)]
    body = []
    for sid in solvers:
        vals = [f1(S.cell(rows, robot, sc).get(sid, {}).get("success_pct", float("nan")))
                for sc in scen]
        row = [S.label(sid)] + vals
        body.append(bold(row) if sid == S.HERO else row)
    header = ["Solver"] + [S.SCEN_LABEL[s] for s in scen]
    write_table(name, caption, label, "l" + "r" * len(scen), header, body)


def tab_latency(rows, name):
    body = []
    for robot, scen in CELLS:
        c = S.cell(rows, robot, scen)
        arm = {"ur5": "UR5", "franka_panda": "Franka"}[robot]
        for sid in ("trac_ik_style", "protein_fast"):
            r = c.get(sid)
            if not r:
                continue
            cells = [f"{arm}/{S.SCEN_LABEL[scen]}", S.label(sid),
                     f1(r["mean_ms"]), f1(r["p50_ms"]), f1(r["p95_ms"]), f1(r["p99_ms"])]
            body.append(bold(cells) if sid == S.HERO else cells)
    write_table(name,
                "Latency (ms): easy vs.\\ hard regime, KineticFold vs.\\ TRAC-IK.",
                "tab:latency", "llrrrr",
                ["Arm/scenario", "Solver", "Mean", "p50", "p95", "p99"], body,
                note="Wall-clock; OS scheduling noise on mean/p95/p99.")


def tab_collision(rows, name):
    solvers = [s for s in ["protein_ik", "multi_start", "trac_ik_style", "protein_fast"]
               if any(r["robot"] == "ur5" and r["solver"] == s for r in rows)]
    scen = [s for s in S.SCENARIOS if S.cell(rows, "ur5", s)]
    body = []
    for sid in solvers:
        succ = [f1(S.cell(rows, "ur5", sc).get(sid, {}).get("success_pct", float("nan")))
                for sc in scen]
        pbc = [f1(S.cell(rows, "ur5", sc).get(sid, {}).get("pb_collision_pct", float("nan")))
               for sc in scen]
        clr_c = S.cell(rows, "ur5", "cluttered").get(sid, {}).get("pb_mean_clearance_m", float("nan"))
        cells = [S.label(sid)] + succ + pbc + [f"{clr_c*1000:+.1f}" if clr_c == clr_c else "--"]
        body.append(bold(cells) if sid == S.HERO else cells)
    header = (["Solver"] + [f"succ {S.SCEN_LABEL[s]}" for s in scen]
              + [f"PB {S.SCEN_LABEL[s]}" for s in scen] + ["clr c (mm)"])
    write_table(name,
                "UR5 real-mesh self-collision. succ = success \\%; "
                "PB = PyBullet self-collision \\%; clr = mean clearance on cluttered.",
                "tab:collision_ur5", "l" + "r" * (len(header) - 1), header, body,
                note="MuJoCo agrees (see \\texttt{mj\\_collision\\_pct}); "
                     "collision reported as a ranking, not an absolute rate.")


def tab_langevin(rows, name, robot="ur5"):
    """LangevinFold vs. the field on UR5: per-scenario real-mesh collision, worst-case
    success, and latency (from the hardest scenario). From the separate small-scale run."""
    order = ["protein_raw", "protein_fast", "trac_ik_style", "multi_start", "protein_ik"]
    solvers = [s for s in order if any(r["robot"] == robot and r["solver"] == s for r in rows)]
    scen = [s for s in S.SCENARIOS if S.cell(rows, robot, s)]
    hard = "cluttered" if "cluttered" in scen else (scen[-1] if scen else None)
    body = []
    for sid in solvers:
        pbc = [f1(S.cell(rows, robot, sc).get(sid, {}).get("pb_collision_pct", float("nan")))
               for sc in scen]
        succs = [S.cell(rows, robot, sc).get(sid, {}).get("success_pct", float("nan")) for sc in scen]
        succs = [s for s in succs if s == s]
        rr = S.cell(rows, robot, hard).get(sid, {}) if hard else {}
        cells = ([S.label(sid)] + pbc
                 + [f1(min(succs) if succs else float("nan")),
                    f1(rr.get("mean_ms", float("nan"))), f1(rr.get("p99_ms", float("nan")))])
        body.append(bold(cells) if sid == "protein_raw" else cells)
    header = ["Solver"] + [f"PB {S.SCEN_LABEL[s]}" for s in scen] + ["succ (min)", "mean ms", "p99 ms"]
    write_table(name,
                "LangevinFold vs.\\ the field on UR5 (separate small-scale run). "
                "PB = PyBullet self-collision \\%; latency from the cluttered cell.",
                "tab:langevin", "l" + "r" * (len(header) - 1), header, body,
                note="LangevinFold gives the lowest real-mesh collision at seconds/solve "
                     "(MuJoCo agrees; see \\texttt{mj\\_collision\\_pct}).")


def tab_dof(json_path, name):
    E = json.loads(Path(json_path).read_text(encoding="utf-8"))["E"]
    dofs = sorted({int(r["dof"]) for r in E})

    def clean_of(sid, d):
        return next((r["clean_pct"] for r in E if int(r["dof"]) == d and r["solver"] == sid),
                    float("nan"))
    body = []
    for d in dofs:
        kf, tr = clean_of("protein_fast", d), clean_of("trac_ik_style", d)
        ratio = f"{kf/tr:.1f}$\\times$" if tr > 0 else ("only solver" if kf > 0 else "--")
        body.append([str(d), f1(kf), f1(tr), ratio])
    write_table(name,
                "Single-shot clean-solve rate (\\%) vs.\\ DOF, planar arm. "
                "Both solvers reach the target $\\approx$100\\%; the gap is self-collision.",
                "tab:dof_scaling", "rrrr",
                ["DOF", "KineticFold", "TRAC-IK", "ratio"], body,
                note="Native, apples-to-apples: KineticFold runs as its C++/Eigen port "
                     "and TRAC-IK as the genuine TRACLabs C++ library (\\texttt{tracikpy}), "
                     "each solving the identical DH chain.")


def tab_dof_full(json_path, name):
    """Table 5, powered version: n=1000/cell, three solvers, CIs, Fisher, feasibility.

    Replaces tab_dof (n=120, two solvers). The extra columns exist because each
    answers a question the old table could not: the CI shows the 16-DOF row is no
    longer one solve; the repeat range shows which solvers are wall-clock
    nondeterministic; Multi-start is the stronger baseline and so carries the
    honest ratio; and the feasibility column separates "the solver failed" from
    "the configuration space admits no clean solution".
    """
    D = json.loads(Path(json_path).read_text(encoding="utf-8"))
    cells, cfg = D["cells"], D["config"]

    def cell(d, s):
        return next(c for c in cells if c["dof"] == d and c["solver"] == s)

    def contrast(d, base):
        return next(c for c in D["contrasts"]
                    if c["dof"] == d and c["baseline"] == base)

    body = []
    for d in cfg["dofs"]:
        kf = cell(d, "protein_fast")
        row = [str(d),
               f"\\textbf{{{kf['clean_pct']:.1f}}} [{kf['ci95_lo']:.1f}, {kf['ci95_hi']:.1f}]"]
        for base in ("trac_ik_style", "multi_start"):
            c = cell(d, base)
            row.append(f"{c['repeat_mean']:.1f} ({c['repeat_min']:.1f}--{c['repeat_max']:.1f})")
        for base in ("trac_ik_style", "multi_start"):
            k = contrast(d, base)
            if k["ratio"] is None:
                row.append("--")
            else:
                mark = "" if k["fisher_p"] < 0.05 else "$^{\\dagger}$"
                row.append(f"{k['ratio']:.1f}$\\times${mark}")
        row.append(f"{kf['feasible_pct']:.1f}" if kf.get("feasible_pct") is not None else "--")
        body.append(row)

    write_table(
        name,
        "Single-shot clean-solve rate (\\%) vs.\\ chain length, planar arm "
        f"($n={cfg['n_per_cell']}$ per cell). All three solvers reach the target "
        "$\\approx$100\\% of the time; the entire gap is self-collision avoidance.",
        "tab:dof_scaling", "r l l l r r r",
        ["DOF", "KineticFold \\% [95\\% CI]", "TRAC-IK \\% (range)",
         "Multi-start \\% (range)", "$\\times$TI", "$\\times$MS", "feasible \\%"],
        body,
        star=True,
        note=(f"$n={cfg['n_per_cell']}$ per cell "
              f"({len(cfg['seeds'])} seeds $\\times$ {cfg['n_per_seed']}). "
              "Native and apples-to-apples: KineticFold as its C++/Eigen port, "
              "TRAC-IK as the genuine TRACLabs C++ library (\\texttt{tracikpy}), "
              "Multi-start as genuine Robotics Toolbox \\texttt{ik\\_LM}, each solving "
              "the identical DH chain. KineticFold is deterministic given the seed and "
              "was bit-identical across all "
              f"{cfg['repeats']} sweep repeats; the two library baselines are wall-clock "
              "budgeted, so their columns give the mean and observed range over those "
              "repeats. Ratios are KineticFold over each baseline; all are significant "
              "at $p<0.05$ (Fisher exact, two-sided) except those marked $^{\\dagger}$. "
              "``feasible'' is the fraction of targets for which \\emph{some} clean "
              "solution was demonstrated by a union oracle over all three solvers "
              "(own $q_0$ plus 384 random restarts each); it is a lower bound, and it "
              "stays high while the solve rates fall by nearly two orders of magnitude "
              "--- so the falling rates measure the difficulty of \\emph{finding} a "
              "clean fold, not the disappearance of one."))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default=str(S.DEFAULT_MASTER_CSV))
    ap.add_argument("--collision-csv", default=str(S.DEFAULT_COLLISION_CSV))
    ap.add_argument("--langevin-csv", default=str(S.DEFAULT_LANGEVIN_CSV))
    ap.add_argument("--json", default=str(S.DEFAULT_USECASE_JSON))
    ap.add_argument("--dof-full-json", default=str(S.DEFAULT_DOF_FULL_JSON))
    args = ap.parse_args()

    master = S.load_rows(args.csv)
    tab_success(master, "ur5", "tab_success_ur5.tex",
                "Success rate (\\%), UR5.", "tab:success_ur5")
    if any(r["robot"] == "franka_panda" for r in master):
        tab_success(master, "franka_panda", "tab_success_franka.tex",
                    "Success rate (\\%), Franka Panda (corrected kinematics).",
                    "tab:success_franka")
    tab_latency(master, "tab_latency.tex")
    # Table 5 now comes from the powered sweep; the legacy n=120 generator is kept
    # so the superseded artifact stays reproducible, but is no longer the default.
    try:
        tab_dof_full(args.dof_full_json, "tab_dof_scaling.tex")
    except FileNotFoundError as e:
        print(f"  [warn] tab_dof_scaling falling back to legacy n=120 run: {e}")
        tab_dof(args.json, "tab_dof_scaling.tex")

    try:
        coll = S.load_rows(args.collision_csv)
        tab_collision(coll, "tab_collision_ur5.tex")
    except FileNotFoundError as e:
        print(f"  [skip] tab_collision_ur5: {e}")

    # tab_langevin is parked for future work — not emitted by the default run.
    # To generate it: uncomment below after running bench/langevin_benchmark.py.
    # try:
    #     tab_langevin(S.load_rows(args.langevin_csv), "tab_langevin.tex")
    # except FileNotFoundError:
    #     print("  [skip] tab_langevin: run bench/langevin_benchmark.py first")


if __name__ == "__main__":
    main()
