"""
Smoke test: our `trac_ik_style` solver vs. TRAC-IK.

WHY THIS EXISTS
---------------
`app/solvers/trac_ik_style.py` is our re-implementation of TRAC-IK's KDL
inverse: damped least squares (DLS) with stuck-detection and random restart.
This script is a *smoke* check — not a rigorous benchmark — that our version
behaves like TRAC-IK on solvable targets (comparable success rate and final
error), so we can trust it as the classical baseline the protein-IK solver
must beat.

TWO MODES (auto-selected)
-------------------------
1. REAL library  — if `tracikpy` is importable AND a URDF is provided
   (env var TRAC_IK_URDF pointing at a URDF whose DH matches the chosen
   robot), we run the genuine TRAC-IK C++/KDL solver and compare.
   This is the real apples-to-apples path.

2. REFERENCE model (fallback, the usual case on Windows where the KDL/orocos
   C++ stack isn't installable) — we compare against a compact, INDEPENDENT
   from-scratch re-implementation of the same DLS+random-restart algorithm,
   coded in THIS file (see `solve_reference_dls`). It shares no code with
   `trac_ik_style.py`, so agreement is a real cross-check: if our production
   solver were broken, a second independent implementation would diverge.

Targets are generated by forward-kinematics of a random config, so every
target is guaranteed reachable (a ground-truth solution exists). That makes
"success rate" a meaningful smoke signal rather than a workspace artifact.

Nothing existing is edited; our solver is treated as a black box via
`run_solver("trac_ik_style", ...)`.

Run (from the `backend/` directory):
    python scrap/trac_ik_smoke.py                 # ur5, 30 trials
    python scrap/trac_ik_smoke.py --robot franka_panda --trials 50
    python scrap/trac_ik_smoke.py --robot planar3dof --seed 7

To exercise the REAL library path (if installed):
    set TRAC_IK_URDF=C:/path/to/ur5.urdf   &&  python scrap/trac_ik_smoke.py
"""
from __future__ import annotations

import argparse
import os
import sys
import time

import numpy as np

# Make `app` importable whether run from backend/ or backend/scrap/.
_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _BACKEND_DIR not in sys.path:
    sys.path.insert(0, _BACKEND_DIR)

from app.core.kinematics import (
    RobotSpec, get_robot_spec, end_effector_pose, geometric_jacobian, pose_error,
    self_collision_min_distance,
)
from app.solvers.registry import run_solver

# Tolerances defining a "solved" pose — match trac_ik_style.py's defaults so
# the two implementations are judged on identical criteria.
POS_TOL = 1e-3      # 1 mm
ORIENT_TOL = 1e-2   # 10 mrad


# ---------------------------------------------------------------------------
# Independent reference implementation of the TRAC-IK KDL algorithm.
# Deliberately NOT importing from app.solvers.trac_ik_style — this is a second,
# separately-written implementation of the same published idea (DLS + random
# restart on stuck) so that matching results actually cross-validate our solver.
# ---------------------------------------------------------------------------
def solve_reference_dls(
    spec: RobotSpec,
    q0: np.ndarray,
    T_target: np.ndarray,
    rng: np.random.Generator,
    max_total_iters: int = 300,
    iters_per_attempt: int = 50,
    stuck_window: int = 8,
    stuck_eps: float = 1e-5,
    damping: float = 0.05,
):
    """Minimal DLS-with-random-restart IK, TRAC-IK-KDL style.

    Returns (success, q_final, pos_err, orient_err, iters, restarts, wall_ms).
    Written from scratch for this smoke test; see module docstring.
    """
    t0 = time.perf_counter()
    q = q0.copy()
    best_q, best_score = q.copy(), np.inf
    total_it, restarts, success = 0, 0, False
    lam2 = damping ** 2
    eye6 = np.eye(6)

    while total_it < max_total_iters:
        history = []
        converged = False
        for _ in range(iters_per_attempt):
            total_it += 1
            err = pose_error(end_effector_pose(spec, q), T_target)
            pos_e = float(np.linalg.norm(err[:3]))
            orient_e = float(np.linalg.norm(err[3:]))
            score = pos_e + 0.3 * orient_e

            if score < best_score:
                best_score, best_q = score, q.copy()

            if pos_e < POS_TOL and orient_e < ORIENT_TOL:
                success, converged, best_q = True, True, q.copy()
                break
            if total_it >= max_total_iters:
                break

            # stuck detection over a sliding window of the scalar score
            history.append(score)
            if len(history) >= stuck_window:
                w = history[-stuck_window:]
                if (w[0] - w[-1]) < stuck_eps:
                    break  # no progress -> abandon attempt, restart

            # damped least squares step
            J = geometric_jacobian(spec, q)
            dq = J.T @ np.linalg.solve(J @ J.T + lam2 * eye6, err)
            q = spec.clip(q + dq)

        if converged or total_it >= max_total_iters:
            break
        restarts += 1
        q = spec.random_config(rng)  # global random restart

    err = pose_error(end_effector_pose(spec, best_q), T_target)
    wall_ms = (time.perf_counter() - t0) * 1000.0
    return (
        success, best_q,
        float(np.linalg.norm(err[:3])), float(np.linalg.norm(err[3:])),
        total_it, restarts, wall_ms,
    )


# ---------------------------------------------------------------------------
# Optional real-library path.
# ---------------------------------------------------------------------------
def try_load_real_tracik():
    """Return a callable (T_target -> (success, pos_err, orient_err, ms)) using
    the genuine TRAC-IK library, or None if unavailable. Requires `tracikpy`
    and a URDF via env var TRAC_IK_URDF matching the chosen robot."""
    urdf = os.environ.get("TRAC_IK_URDF")
    if not urdf:
        return None, "TRAC_IK_URDF env var not set"
    if not os.path.exists(urdf):
        return None, f"URDF not found: {urdf}"
    try:
        from tracikpy import TracIKSolver  # type: ignore
    except Exception as e:  # noqa: BLE001
        return None, f"tracikpy not importable ({e})"

    base = os.environ.get("TRAC_IK_BASE_LINK", "base_link")
    tip = os.environ.get("TRAC_IK_TIP_LINK", "tool0")
    try:
        ik = TracIKSolver(urdf, base, tip)
    except Exception as e:  # noqa: BLE001
        return None, f"TracIKSolver init failed ({e})"

    def run(T_target: np.ndarray):
        t0 = time.perf_counter()
        q = ik.ik(T_target, qinit=np.zeros(ik.number_of_joints))
        ms = (time.perf_counter() - t0) * 1000.0
        if q is None:
            return False, np.inf, np.inf, ms
        err = pose_error(ik.fk(q), T_target)
        return True, float(np.linalg.norm(err[:3])), float(np.linalg.norm(err[3:])), ms

    return run, f"real TRAC-IK ({urdf}, {base}->{tip})"


# ---------------------------------------------------------------------------
# Smoke run
# ---------------------------------------------------------------------------
def main() -> int:
    p = argparse.ArgumentParser(description="Smoke: trac_ik_style vs TRAC-IK")
    p.add_argument("--robot", default="ur5",
                   choices=["ur5", "franka_panda", "planar3dof"])
    p.add_argument("--trials", type=int, default=30)
    p.add_argument("--seed", type=int, default=0)
    args = p.parse_args()

    try:
        sys.stdout.reconfigure(encoding="utf-8")  # Windows console friendliness
    except Exception:  # noqa: BLE001
        pass

    spec = get_robot_spec(args.robot)
    rng = np.random.default_rng(args.seed)

    real_run, real_note = try_load_real_tracik()
    baseline_label = "REAL TRAC-IK" if real_run else "REFERENCE DLS (independent)"

    print(f"=== TRAC-IK smoke: '{args.robot}', {args.trials} reachable targets, "
          f"seed={args.seed} ===")
    print(f"Baseline mode : {baseline_label}")
    if not real_run:
        print(f"  (real library not used: {real_note})")
        print("  -> comparing against a from-scratch re-implementation of the "
              "same DLS+restart algorithm.")
    print()

    # per-trial data, index 0 = ours, 1 = baseline
    ok = [[], []]           # bool solved
    pos = [[], []]          # position error (m)
    orient = [[], []]       # orientation error (rad)
    ms = [[], []]           # wall time (ms)
    mind = [[], []]         # self-collision min distance (m); None if not modelled
    sum_restarts_ours = 0

    for t in range(args.trials):
        q_ref = spec.random_config(rng)                 # ground-truth config
        T_target = end_effector_pose(spec, q_ref)       # -> guaranteed reachable
        q0 = spec.random_config(rng)                    # independent start seed
        solver_rng = np.random.default_rng(1000 + t)    # deterministic per trial

        # --- our production solver (black box) ---
        r = run_solver("trac_ik_style", spec, q0, T_target,
                       np.random.default_rng(2000 + t))
        ok[0].append(bool(r.success) and r.pos_error < POS_TOL and r.orient_error < ORIENT_TOL)
        pos[0].append(r.pos_error)
        orient[0].append(r.orient_error)
        ms[0].append(r.wall_time_ms)
        mind[0].append(r.min_self_distance)   # our solver reports it directly
        sum_restarts_ours += r.restarts

        # --- baseline ---
        if real_run:
            # real TRAC-IK runs its own URDF kinematics; our capsule collision
            # model doesn't correspond to its links, so collision is left N/A.
            b_ok, pe, oe, t_ms = real_run(T_target)
            mind[1].append(None)
        else:
            b_ok, q_b, pe, oe, _it, _rs, t_ms = solve_reference_dls(
                spec, q0, T_target, solver_rng)
            # same shared collision model as our solver -> directly comparable
            mind[1].append(self_collision_min_distance(spec, q_b))
        ok[1].append(bool(b_ok) and pe < POS_TOL and oe < ORIENT_TOL)
        pos[1].append(pe if np.isfinite(pe) else np.nan)
        orient[1].append(oe if np.isfinite(oe) else np.nan)
        ms[1].append(t_ms)

    N = args.trials
    rows = [("trac_ik_style (ours)", 0), (baseline_label, 1)]

    def _collfree(i):
        """Collision-free rate among SOLVED configs (unsolved poses are moot).
        Returns None when collision isn't modelled for this baseline."""
        vals = [d for d, s in zip(mind[i], ok[i]) if s and d is not None]
        if not vals:
            return None
        return sum(1 for d in vals if d >= 0.0) / len(vals)

    # --- accuracy / success table ---
    hdr = (f"{'Solver':<30} {'Success%':>9} {'Mean pos(mm)':>13} "
           f"{'Mean orient(mrad)':>18} {'Coll-free%':>11}")
    print(hdr)
    print("-" * len(hdr))
    for label, i in rows:
        cf = _collfree(i)
        cf_s = "     n/a" if cf is None else f"{100.0 * cf:>10.1f}%"
        print(f"{label:<30} "
              f"{100.0 * np.mean(ok[i]):>8.1f}% "
              f"{1000.0 * np.nanmean(pos[i]):>13.3f} "
              f"{1000.0 * np.nanmean(orient[i]):>18.3f} "
              f"{cf_s:>11}")

    # --- latency table (tail matters for real-time IK) ---
    print()
    lhdr = (f"{'Solver':<30} {'Mean ms':>9} {'p50 ms':>9} {'p95 ms':>9} {'Max ms':>9}")
    print(lhdr)
    print("-" * len(lhdr))
    for label, i in rows:
        a = np.array(ms[i])
        print(f"{label:<30} "
              f"{a.mean():>9.2f} "
              f"{np.percentile(a, 50):>9.2f} "
              f"{np.percentile(a, 95):>9.2f} "
              f"{a.max():>9.2f}")
    print(f"\n(ours used {sum_restarts_ours} random restarts total, "
          f"{sum_restarts_ours / N:.2f}/trial)")

    # --- smoke verdict ---
    ours_rate = float(np.mean(ok[0]))
    base_rate = float(np.mean(ok[1]))
    ours_cf = _collfree(0)
    ours_p95 = float(np.percentile(ms[0], 95))
    # PASS if: ours solves a healthy fraction of reachable targets AND is not
    # materially worse than the baseline (allow a 15pp slack for the stochastic
    # nature of random-restart on a small smoke sample).
    healthy = ours_rate >= 0.60
    not_worse = ours_rate >= base_rate - 0.15
    passed = healthy and not_worse

    print()
    extra = f" | p95 {ours_p95:.1f} ms"
    if ours_cf is not None:
        extra += f" | {ours_cf:.0%} collision-free"
    if passed:
        print(f"SMOKE PASS  — ours {ours_rate:.0%} vs baseline {base_rate:.0%} "
              f"on reachable targets{extra}.")
    else:
        why = []
        if not healthy:
            why.append(f"ours only solved {ours_rate:.0%} of reachable targets (<60%)")
        if not not_worse:
            why.append(f"ours {ours_rate:.0%} trails baseline {base_rate:.0%} by >15pp")
        print("SMOKE FAIL  — " + "; ".join(why))
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
